
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 1

project_name: palworld_exporter

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Revision={{ .Commit }}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - 'jimmysharp/{{.ProjectName}}:latest-amd64'
      - 'jimmysharp/{{.ProjectName}}:{{.Version}}-amd64'
    build_flag_templates:
      - '--platform=linux/amd64'
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - 'jimmysharp/{{.ProjectName}}:latest-arm64v8'
      - 'jimmysharp/{{.ProjectName}}:{{.Version}}-arm64v8'
    build_flag_templates:
      - '--platform=linux/arm64/v8'
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: 'jimmysharp/{{.ProjectName}}:latest'
    image_templates:
      - 'jimmysharp/{{.ProjectName}}:latest-amd64'
      - 'jimmysharp/{{.ProjectName}}:latest-arm64v8'
  - name_template: 'jimmysharp/{{.ProjectName}}:{{.Version}}'
    image_templates:
      - 'jimmysharp/{{.ProjectName}}:{{.Version}}-amd64'
      - 'jimmysharp/{{.ProjectName}}:{{.Version}}-arm64v8'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
