FROM golang:1.24.1-bookworm

# renovate: datasource=go depName=github.com/golangci/golangci-lint packageName=github.com/golangci/golangci-lint
ARG GOLANGCI_LINT_VERSION=v1.64.8

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}