FROM golang:1.26.0-bookworm

# renovate: datasource=go depName=github.com/golangci/golangci-lint packageName=github.com/golangci/golangci-lint
ARG GOLANGCI_LINT_VERSION=v2.9.0

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}