name: PR Checks

on:
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
  checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      
      - name: Lint checks
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57
